SELECT * FROM MEMBER

SELECT Id,Name INTO MEMBER2 FROM MEMBER WHERE 1=2

SELECT Id AS MemberId,Name AS MenberName INTO MEMBER2 FROM MEMBER WHERE 1=2

SELECT * FROM MEMBER2

DROP TABLE MEMBER2

SELECT FirstName, 'SUM OF SALARY'=SUM(SALARY) FROM Employees
GROUP BY FirstName;


SELECT COALESCE(NULL, NULL, NULL, 'W3Schools.com', NULL, 'Example.com');
SELECT COALESCE(NULL, 1, 2, 'W3Schools.com');

SELECT IIF(500<1000, 'YES', 'NO');

SELECT ISNULL(NULL, 'W3Schools.com');
SELECT ISNULL('Hello', 'W3Schools.com');
SELECT ISNULL(NULL, 500);

