
CREATE FUNCTION CALCULATE_PF (@BASICSALARY INT)
RETURNS	int
AS
BEGIN
	DECLARE @RES int
	SET @RES = @BASICSALARY*.12
	RETURN @RES
END

SELECT dbo.CALCULATE_PF(5000) AS PF

SELECT First_Name,Salary,dbo.CALCULATE_PF(Salary) AS 'PF' FROM Employees2
