CREATE TABLE ACCOUNTS
(
	ACCNO INT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	BALANCE INT NOT NULL DEFAULT 0
)

DELETE FROM ACCOUNTS

INSERT INTO ACCOUNTS (ACCNO,NAME) VALUES (101,'A')
INSERT INTO ACCOUNTS (ACCNO,NAME,BALANCE) VALUES (102,'B',2000)
INSERT INTO ACCOUNTS (ACCNO,NAME,BALANCE) VALUES (103,'C',5000)
INSERT INTO ACCOUNTS (ACCNO,NAME,BALANCE) VALUES (104,'D',1500)
INSERT INTO ACCOUNTS (ACCNO,NAME,BALANCE) VALUES (105,'E',400)

SELECT * FROM ACCOUNTS


--Transfering Rs.1000 from 104 to 101


BEGIN TRANSACTION money_transfer

DECLARE @avl_bal INT
SELECT @avl_bal=BALANCE FROM ACCOUNTS WHERE ACCNO = 104

IF(@avl_bal>0)
BEGIN
	SET NOCOUNT ON
	UPDATE ACCOUNTS 
	SET BALANCE = BALANCE - 1000
	WHERE ACCNO = 104

	UPDATE ACCOUNTS 
	SET BALANCE = BALANCE + 1000
	WHERE ACCNO = 101

	PRINT ('MONEY TRANSFERED')
END
ELSE
	PRINT('INSUFFICIENT BALANCE')

COMMIT TRANSACTION money_taranfer

