CREATE DATABASE SQLPRACTICE
GO
USE SQLPRACTICE

CREATE TABLE DEPARTMENT(
	DEPT_ID INT,
	DEPT_NAME VARCHAR(50) NOT NULL,
	CONSTRAINT PK_DEPTID PRIMARY KEY(DEPT_ID)
)

CREATE TABLE EMPLOYEE(
	ID INT IDENTITY (1,1),
	NAME VARCHAR(50) NOT NULL,
	CITY VARCHAR(50) DEFAULT 'AHMEDABAD',
	ADATE DATE DEFAULT GETDATE(),
	DEPT_ID INT,
	CONSTRAINT PK_EID PRIMARY KEY(ID),
	CONSTRAINT FK_DEPT_ID FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
)

INSERT INTO DEPARTMENT VALUES(1,'COMPUTER')
INSERT INTO DEPARTMENT VALUES(2,'EC')
INSERT INTO DEPARTMENT VALUES(3,'CIVIL')



INSERT INTO EMPLOYEE(NAME,DEPT_ID) VALUES ('GAUTAM',1)
INSERT INTO EMPLOYEE(NAME,CITY,DEPT_ID) VALUES ('YASH','JUNAGADH',2)
INSERT INTO EMPLOYEE(NAME,DEPT_ID) VALUES ('SAUMTYA',1)

SELECT * FROM DEPARTMENT
SELECT * FROM EMPLOYEE


ALTER TABLE EMPLOYEE
ADD SALARY INT 

ALTER TABLE EMPLOYEE
DROP COLUMN SALARY

UPDATE EMPLOYEE
SET SALARY = 5000

UPDATE EMPLOYEE 
SET SALARY = SALARY+5000
WHERE DEPT_ID=1

UPDATE EMPLOYEE 
SET SALARY = SALARY + 5000
WHERE DEPT_ID IN  ( SELECT DEPT_ID FROM DEPARTMENT WHERE DEPT_NAME='COMPUTER')




UPDATE E1
SET E1.SALARY=E1.SALARY+5000
FROM EMPLOYEE E1 JOIN DEPARTMENT D1
ON E1.DEPT_ID = D1.DEPT_ID
WHERE D1.DEPT_NAME = 'COMPUTER'


SELECT *  INTO EMPTEST FROM EMPLOYEE

SELECT * FROM EMPTEST


CREATE OR ALTER PROC SP_MYPROC @ID INT,@SAL INT OUTPUT
AS
	SELECT @SAL=SALARY FROM EMPLOYEE WHERE ID = @ID;
	--SELECT * FROM DEPARTMENT



	DECLARE @SAL INT
	EXEC SP_MYPROC 1, @SAL OUTPUT
	PRINT @SAL


DECLARE MY_CURSOR CURSOR 
FOR
SELECT SALARY FROM EMPLOYEE

DECLARE @SAL INT;

OPEN MY_CURSOR
 
 FETCH NEXT FROM MY_CURSOR INTO @SAL;

 WHILE @@FETCH_STATUS=0
 BEGIN
	PRINT @SAl


	 FETCH NEXT FROM MY_CURSOR INTO @SAL;

 END

 CLOSE MY_CURSOR
 DEALLOCATE MY_CURSOR


 SELECT * FROM DEPARTMENT
SELECT * FROM EMPLOYEE

 SELECT D.DEPT_ID,D.DEPT_NAME,COUNT(E.NAME) AS 'NO OF EMPLOYEE'
 FROM DEPARTMENT D LEFT JOIN EMPLOYEE E
 ON D.DEPT_ID = E.DEPT_ID
 GROUP BY D.DEPT_ID,D.DEPT_NAME


 CREATE TRIGGER TRIG_DEPT
 ON DEPARTMENT
 FOR INSERT 
 AS
 BEGIN
	SELECT * FROM inserted
 END

 INSERT INTO DEPARTMENT VALUES(5,'NEW ADDED')

 SELECT * FROM DEPARTMENT