CREATE VIEW VW_EMP_INC2
AS
SELECT e1.First_Name,i1.INCENTIVE_AMOUNT 
FROM Employees e1 JOIN Incentives i1
ON e1.Employee_Id = i1.Employee_ref_id
WHERE i1.INCENTIVE_AMOUNT>3000

SELECT * FROM VW_EMP_INC2