SELECT * FROM employees
SELECT * FROM departments
SELECT * FROM locations

CREATE VIEW VW_EMP_TASK8
AS
SELECT d1.DEPARTMENT_NAME,e1.FIRST_NAME,l1.CITY FROM
employees e1 JOIN departments d1 
ON d1.MANAGER_ID=e1.EMPLOYEE_ID
JOIN locations l1
ON d1.LOCATION_ID=l1.LOCATION_ID

SELECT * FROM VW_EMP_TASK8