SELECT * FROM employees
SELECT * FROM departments

CREATE VIEW VW_EMP_TASK9
AS
SELECT d1.DEPARTMENT_NAME,(e1.FIRST_NAME+' '+e1.LAST_NAME) AS 'Names',e1.HIRE_DATE,e1.SALARY FROM
employees e1 JOIN departments d1 
ON d1.MANAGER_ID=e1.EMPLOYEE_ID
WHERE DATEDIFF(YEAR,e1.HIRE_DATE,GETDATE())>15


SELECT * FROM VW_EMP_TASK9