SELECT * FROM Employees


-- CREATE VIEW

CREATE VIEW VW_EMPLOYEES AS
SELECT Employee_Id,FirstName, LastName
FROM Employees

SELECT * FROM VW_EMPLOYEES


-- DROP VIEW
DROP VIEW VW_EMPLOYEES

SELECT FirstName FROM VW_EMPLOYEES WHERE Employee_Id=1


--UPDATE VIEW
UPDATE VW_EMPLOYEES
SET FirstName = 'ABC'
WHERE Employee_Id=8


--DELETE FROM VIEW
DELETE FROM VW_EMPLOYEES
WHERE Employee_Id=9